name: shuffler_web_ui
description: UI for Shuffler - asset management tool
version: 0.0.1
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  angular2: ^3.0.0
  browser: ^0.10.0
  http: ^0.11.3+9
  path: ^1.3.9
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  ng2gen: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
#        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
        Window: 'dart:html'
    mirror_mode: release
- $dart2js:
    minify: true

#    sourceMaps: true
#    commandLineOptions: [--enable-experimental-mirrors]
- dart_to_js_script_rewriter
